/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Hospital Employee List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface EmployeeListEntry
 */
export interface EmployeeListEntry {
    /**
     * Unique id of the entry in this waiting list
     * @type {string}
     * @memberof EmployeeListEntry
     */
    'id': string;
    /**
     * Name of patient in waiting list
     * @type {string}
     * @memberof EmployeeListEntry
     */
    'name': string;
    /**
     * Unique identifier of the patient known to Web-In-Cloud system
     * @type {string}
     * @memberof EmployeeListEntry
     */
    'patientId': string;
    /**
     * Name of the job position
     * @type {string}
     * @memberof EmployeeListEntry
     */
    'jobTitle': string;
    /**
     * Unique identifier of the timesheet
     * @type {string}
     * @memberof EmployeeListEntry
     */
    'timesheet': string;
}
/**
 * Describes the schedule of hospital employee
 * @export
 * @interface Timesheet
 */
export interface Timesheet {
    /**
     * Unique identifier of the timesheet
     * @type {string}
     * @memberof Timesheet
     */
    'id': string;
    /**
     * number of hours worked that day
     * @type {number}
     * @memberof Timesheet
     */
    'hours': number;
    /**
     * description of the shift
     * @type {string}
     * @memberof Timesheet
     */
    'description': string;
    /**
     * day of the shift
     * @type {string}
     * @memberof Timesheet
     */
    'date': string;
}

/**
 * JkaEmployeeListApi - axios parameter creator
 * @export
 */
export const JkaEmployeeListApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * By using ambulanceId you get list of employees in hospital
         * @summary Provides the ambulance waiting list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeListEntries: async (ambulanceId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getEmployeeListEntries', 'ambulanceId', ambulanceId)
            const localVarPath = `/employee-list/{ambulanceId}/entries`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JkaEmployeeListApi - functional programming interface
 * @export
 */
export const JkaEmployeeListApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JkaEmployeeListApiAxiosParamCreator(configuration)
    return {
        /**
         * By using ambulanceId you get list of employees in hospital
         * @summary Provides the ambulance waiting list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEmployeeListEntries(ambulanceId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EmployeeListEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEmployeeListEntries(ambulanceId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * JkaEmployeeListApi - factory interface
 * @export
 */
export const JkaEmployeeListApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JkaEmployeeListApiFp(configuration)
    return {
        /**
         * By using ambulanceId you get list of employees in hospital
         * @summary Provides the ambulance waiting list
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeListEntries(ambulanceId: string, options?: any): AxiosPromise<Array<EmployeeListEntry>> {
            return localVarFp.getEmployeeListEntries(ambulanceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JkaEmployeeListApi - interface
 * @export
 * @interface JkaEmployeeListApi
 */
export interface JkaEmployeeListApiInterface {
    /**
     * By using ambulanceId you get list of employees in hospital
     * @summary Provides the ambulance waiting list
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JkaEmployeeListApiInterface
     */
    getEmployeeListEntries(ambulanceId: string, options?: AxiosRequestConfig): AxiosPromise<Array<EmployeeListEntry>>;

}

/**
 * JkaEmployeeListApi - object-oriented interface
 * @export
 * @class JkaEmployeeListApi
 * @extends {BaseAPI}
 */
export class JkaEmployeeListApi extends BaseAPI implements JkaEmployeeListApiInterface {
    /**
     * By using ambulanceId you get list of employees in hospital
     * @summary Provides the ambulance waiting list
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JkaEmployeeListApi
     */
    public getEmployeeListEntries(ambulanceId: string, options?: AxiosRequestConfig) {
        return JkaEmployeeListApiFp(this.configuration).getEmployeeListEntries(ambulanceId, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * JkaTimesheetApi - axios parameter creator
 * @export
 */
export const JkaTimesheetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * By using ambulanceId you get timesheet of employees in hospital
         * @summary Provides the timesheet
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {string} timesheetId pass the id of the particular timesheet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeTimesheet: async (ambulanceId: string, timesheetId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ambulanceId' is not null or undefined
            assertParamExists('getEmployeeTimesheet', 'ambulanceId', ambulanceId)
            // verify required parameter 'timesheetId' is not null or undefined
            assertParamExists('getEmployeeTimesheet', 'timesheetId', timesheetId)
            const localVarPath = `/timesheet/{ambulanceId}/{timesheetId}`
                .replace(`{${"ambulanceId"}}`, encodeURIComponent(String(ambulanceId)))
                .replace(`{${"timesheetId"}}`, encodeURIComponent(String(timesheetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JkaTimesheetApi - functional programming interface
 * @export
 */
export const JkaTimesheetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JkaTimesheetApiAxiosParamCreator(configuration)
    return {
        /**
         * By using ambulanceId you get timesheet of employees in hospital
         * @summary Provides the timesheet
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {string} timesheetId pass the id of the particular timesheet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEmployeeTimesheet(ambulanceId: string, timesheetId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Timesheet>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEmployeeTimesheet(ambulanceId, timesheetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * JkaTimesheetApi - factory interface
 * @export
 */
export const JkaTimesheetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JkaTimesheetApiFp(configuration)
    return {
        /**
         * By using ambulanceId you get timesheet of employees in hospital
         * @summary Provides the timesheet
         * @param {string} ambulanceId pass the id of the particular ambulance
         * @param {string} timesheetId pass the id of the particular timesheet
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEmployeeTimesheet(ambulanceId: string, timesheetId: string, options?: any): AxiosPromise<Array<Timesheet>> {
            return localVarFp.getEmployeeTimesheet(ambulanceId, timesheetId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JkaTimesheetApi - interface
 * @export
 * @interface JkaTimesheetApi
 */
export interface JkaTimesheetApiInterface {
    /**
     * By using ambulanceId you get timesheet of employees in hospital
     * @summary Provides the timesheet
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {string} timesheetId pass the id of the particular timesheet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JkaTimesheetApiInterface
     */
    getEmployeeTimesheet(ambulanceId: string, timesheetId: string, options?: AxiosRequestConfig): AxiosPromise<Array<Timesheet>>;

}

/**
 * JkaTimesheetApi - object-oriented interface
 * @export
 * @class JkaTimesheetApi
 * @extends {BaseAPI}
 */
export class JkaTimesheetApi extends BaseAPI implements JkaTimesheetApiInterface {
    /**
     * By using ambulanceId you get timesheet of employees in hospital
     * @summary Provides the timesheet
     * @param {string} ambulanceId pass the id of the particular ambulance
     * @param {string} timesheetId pass the id of the particular timesheet
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JkaTimesheetApi
     */
    public getEmployeeTimesheet(ambulanceId: string, timesheetId: string, options?: AxiosRequestConfig) {
        return JkaTimesheetApiFp(this.configuration).getEmployeeTimesheet(ambulanceId, timesheetId, options).then((request) => request(this.axios, this.basePath));
    }
}


