/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Hospital Employee List management for Web-In-Cloud system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: kapusta.jergus@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

