/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JkaApp {
        "ambulanceId": string;
        "apiBase": string;
        "basePath": string;
    }
    interface JkaEmployeeList {
        "apiBase": string;
    }
    interface JkaTimesheet {
        "ambulanceId": string;
        "apiBase": string;
        "worker": string;
    }
}
declare global {
    interface HTMLJkaAppElement extends Components.JkaApp, HTMLStencilElement {
    }
    var HTMLJkaAppElement: {
        prototype: HTMLJkaAppElement;
        new (): HTMLJkaAppElement;
    };
    interface HTMLJkaEmployeeListElement extends Components.JkaEmployeeList, HTMLStencilElement {
    }
    var HTMLJkaEmployeeListElement: {
        prototype: HTMLJkaEmployeeListElement;
        new (): HTMLJkaEmployeeListElement;
    };
    interface HTMLJkaTimesheetElement extends Components.JkaTimesheet, HTMLStencilElement {
    }
    var HTMLJkaTimesheetElement: {
        prototype: HTMLJkaTimesheetElement;
        new (): HTMLJkaTimesheetElement;
    };
    interface HTMLElementTagNameMap {
        "jka-app": HTMLJkaAppElement;
        "jka-employee-list": HTMLJkaEmployeeListElement;
        "jka-timesheet": HTMLJkaTimesheetElement;
    }
}
declare namespace LocalJSX {
    interface JkaApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "basePath"?: string;
    }
    interface JkaEmployeeList {
        "apiBase"?: string;
    }
    interface JkaTimesheet {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "worker"?: string;
    }
    interface IntrinsicElements {
        "jka-app": JkaApp;
        "jka-employee-list": JkaEmployeeList;
        "jka-timesheet": JkaTimesheet;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jka-app": LocalJSX.JkaApp & JSXBase.HTMLAttributes<HTMLJkaAppElement>;
            "jka-employee-list": LocalJSX.JkaEmployeeList & JSXBase.HTMLAttributes<HTMLJkaEmployeeListElement>;
            "jka-timesheet": LocalJSX.JkaTimesheet & JSXBase.HTMLAttributes<HTMLJkaTimesheetElement>;
        }
    }
}
