openapi: 3.0.0
servers:
  - description: Cluster Endpoint
    url: /api
info:
  description: Hospital Employee List management for Web-In-Cloud system
  version: "1.0.0"
  title: Waiting List Api
  contact:
    email: kapusta.jergus@gmail.com
  license:
    name: CC BY 4.0
    url: "https://creativecommons.org/licenses/by/4.0/"
tags:
- name: jka-employee-list
  description: Hospital Employee List API
- name: jka-timesheet
  description: Hospital Employee List API 
paths:
  "/employee-list/{ambulanceId}/entries":
    get:
      tags:
        - jka-employee-list
      summary: Provides the ambulance waiting list
      operationId: getEmployeeListEntries
      description: By using ambulanceId you get list of employees in hospital
      parameters:
        - in: path
          name: ambulanceId
          description: pass the id of the particular ambulance
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the waiting list entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EmployeeListEntry"
              examples:
                response:
                  $ref: "#/components/examples/EmployeeListEntriesExample"
        "404":
          description: Ambulance with such ID does not exist
  "/timesheet/{ambulanceId}/{timesheetId}":
    get:
      tags:
        - jka-timesheet
      summary: Provides the timesheet
      operationId: getEmployeeTimesheet
      description: By using ambulanceId you get timesheet of employees in hospital
      parameters:
        - in: path
          name: ambulanceId
          description: pass the id of the particular ambulance
          required: true
          schema:
            type: string
        - in: path
          name: timesheetId
          description: pass the id of the particular timesheet
          required: true
          schema:
            type: string
      responses:
        "200":
          description: value of the waiting list entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Timesheet"
              examples:
                response:
                  $ref: "#/components/examples/TimesheetsExample"
        "404":
          description: Ambulance with such ID does not exist
components:
  schemas:
    EmployeeListEntry:
      type: object
      required: [id, patientId, jobTitle, name, timesheet]
      properties:
        id:
          type: string
          example: x321ab3
          description: Unique id of the entry in this waiting list
        name:
          type: string
          example: Jožko Púčik
          description: Name of patient in waiting list
        patientId:
          type: string
          example: 460527-jozef-pucik
          description: Unique identifier of the patient known to Web-In-Cloud system
        jobTitle:
          type: string
          example: "Doctor"
          description: Name of the job position
        timesheet:
          type: string
          example: "12321"
          description: Unique identifier of the timesheet
      example:
        $ref: "#/components/examples/EmployeeListEntryExample"
    Timesheet:
      description: "Describes the schedule of hospital employee"
      required: [id, date, hours, description]
      properties:
        id: 
          type: string
          example: "12321"
          description: Unique identifier of the timesheet
        hours:
          type: integer
          format: int32
          example: 8
          description: number of hours worked that day
        description:
          type: string
          example: "Driving and ambulance"
          description: description of the shift
        date:
          type: string
          format: date-time
          example: "2038-12-24T10:35:00Z"
          description: day of the shift
      example:
        $ref: "#/components/examples/TimesheetExample"
  examples:
    EmployeeListEntryExample:
      summary: employee Jožko Púčik
      description: |
        Entry represents a hospital employee
      value:
        id: x321ab3
        name: Jožko Púčik
        patientId: 460527-jozef-pucik
        jobTitle: "Doctor"
        timesheet: "12321"
    TimesheetExample:
      summary: Timesheet entries
      description: list of working days
      value:
        id: "12321"
        hours: 8
        description: "Driving and ambulance"
        date:  "2023-12-24T10:35:00Z"
    EmployeeListEntriesExample:
      summary: List of employees
      description: |
        Example list of hospital employees
      value:
      - id: x321ab3
        name: Jožko Púčik
        patientId: 460527-jozef-pucik
        jobTitle: "Doctor"
        timesheet: "12321"
      - id: a322ag9
        name: Marek Medzny
        patientId: 460527-marek-medzny
        jobTitle: "Primar"
        timesheet: "123"
    TimesheetsExample:
      summary: Timesheet entries
      description: list of working days
      value:
      - id: "12321"
        hours: 8
        description: "Driving and ambulance"
        date:  "2023-12-24T10:35:00Z"
      - id: "12321"
        hours: 5
        description: "Driving and ambulance1"
        date:  "2023-12-25T10:35:00Z"
      - id: "12321"
        hours: 7
        description: "Driving and ambulance2"
        date:  "2023-12-26T10:35:00Z"
      - id: "12322"
        hours: 11
        description: "Doing an operation"
        date:  "2023-12-26T11:35:00Z"